// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu7mt7Vyp661KU01P8JXie4pr7qrfE2X0',
    appId: '1:371457439281:web:0c2ebfa37518af747e8710',
    messagingSenderId: '371457439281',
    projectId: 'chatapp-b7e85',
    authDomain: 'chatapp-b7e85.firebaseapp.com',
    storageBucket: 'chatapp-b7e85.firebasestorage.app',
    measurementId: 'G-0CTNKK3W89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR8t8VjbOKkWOdax4qS6XZTB1AknnIBeI',
    appId: '1:371457439281:android:f1e0cb9d9576e10b7e8710',
    messagingSenderId: '371457439281',
    projectId: 'chatapp-b7e85',
    storageBucket: 'chatapp-b7e85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZqjTuaFuPu8PNOnx6kUPmOcKnkFmC_Wk',
    appId: '1:371457439281:ios:0cf8cf49202705ab7e8710',
    messagingSenderId: '371457439281',
    projectId: 'chatapp-b7e85',
    storageBucket: 'chatapp-b7e85.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZqjTuaFuPu8PNOnx6kUPmOcKnkFmC_Wk',
    appId: '1:371457439281:ios:0cf8cf49202705ab7e8710',
    messagingSenderId: '371457439281',
    projectId: 'chatapp-b7e85',
    storageBucket: 'chatapp-b7e85.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu7mt7Vyp661KU01P8JXie4pr7qrfE2X0',
    appId: '1:371457439281:web:474c2d6a80f497787e8710',
    messagingSenderId: '371457439281',
    projectId: 'chatapp-b7e85',
    authDomain: 'chatapp-b7e85.firebaseapp.com',
    storageBucket: 'chatapp-b7e85.firebasestorage.app',
    measurementId: 'G-1SFW4WE164',
  );
}
